# /usr/bin/perl -w

# Generate usys.S the stubs for syscalls.


print "# generated by usys.pl -- do not edit\n";

print "#include \"kern/libs/sysnum.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}

entry("brk");
entry("chdir");
entry("clone");
entry("close");
entry("dup");
entry("dup3");
entry("execve");
entry("exit");
entry("fork");
entry("fstat");
entry("getcwd");
entry("getdents64");
entry("getpid");
entry("getppid");
entry("gettimeofday");
entry("linkat");
entry("mmap");
entry("mkdirat");
entry("mount");
entry("munmap");
entry("nanosleep");
entry("open");
entry("pipe2");
entry("read");
entry("sched_yield");
entry("times");
entry("unlinkat");
entry("umount2");
entry("uname");
entry("wait");
entry("wait4");
entry("write");
